-- CI: the headline theorems must rest only on Lean's standard axioms.
-- Run with `lake env lean spec/scripts/axioms.lean`; CI fails on `sorryAx`.
-- Theorem names are added here by the task that proves them.
import Deflate
open Deflate
#print axioms Deflate.byteAt_oob
#print axioms Deflate.readBits_pos
#print axioms Deflate.readBits_bytes
#print axioms Deflate.readBits_lt
#print axioms Deflate.readBits_eof
#print axioms Deflate.alignToByte_idem
#print axioms Deflate.readHeader_pos
#print axioms Deflate.readStored_aligned
#print axioms Deflate.readStored_consumes
#print axioms Deflate.readStored_rejects_bad_nlen
#print axioms Deflate.fixedLitLen_complete
#print axioms Deflate.fixedDist_complete
#print axioms Deflate.decodeSym_pos
#print axioms Deflate.decodeSym_bytes
#print axioms Deflate.decodeSym_in_range
#print axioms Deflate.decodeSym_local
#print axioms Deflate.decodeSymFast_eq
#print axioms Deflate.buildTable_size
#print axioms Deflate.tableEntry_some
#print axioms Deflate.readBits_some
#print axioms Deflate.fixedLitLen_table_total
#print axioms Deflate.fixedDist_table_total
#print axioms Deflate.copyBack_size
#print axioms Deflate.copyBack_overlap
#print axioms Deflate.copyBack_rejects
#print axioms Deflate.readLength_range
#print axioms Deflate.readDistance_range
#print axioms Deflate.decodeHuffBlock_monotone
#print axioms Deflate.decodeHuffBlock_within_limit
#print axioms Deflate.decodeHuffBlock_progress
#print axioms Deflate.clOrder_is_a_permutation
#print axioms Deflate.readDynamicCodes_valid
#print axioms Deflate.readDynamicCodes_pos
#print axioms Deflate.decode_deterministic
#print axioms Deflate.decode_within_limit
#print axioms Deflate.encodeStored_empty
#print axioms Deflate.encodeStored_valid
#print axioms Deflate.decode_encodeStored
#print axioms Deflate.expand_compressTokens
#print axioms Deflate.compressTokens_valid
#print axioms Deflate.valid_iff_prefix
#print axioms Deflate.toBytes_bitAt
#print axioms Deflate.readBits_written
#print axioms Deflate.agree_written
#print axioms Deflate.agree_patternReader_written
#print axioms Deflate.decodeSym_written
#print axioms Deflate.decodeSym_writeCode
#print axioms Deflate.bitAt_writeCode
#print axioms Deflate.fixedLit_code_decodes
#print axioms Deflate.fixedDist_code_decodes
#print axioms Deflate.lengthSym_reads
#print axioms Deflate.distSym_reads
#print axioms Deflate.decode_emitFixed
#print axioms Deflate.decode_compress
